name: Release Extension

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags like v1.0.0

jobs:
  package-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Compile
      run: npm run compile

    - name: Package extension
      run: |
        npm install -g vsce
        vsce package

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.vsix'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
